### ISSUE TITLE
Failed to load optimized model

### ISSUE THREAD

**Issue by abada** [hansemannn/Ti.GoogleMaps#10] opened 2016-02-29 21:54 UTC
I am using `de.hansknoechel.googlemaps`  `1.0.2'  `TISDK 5.1.2.GA`  because the latest version doesn`t work in `TISDK 5.2.0.GA`
```
`CoreData: Failed to load optimized model at path '/Users/abdellatifhenno/my.app/GoogleMaps.bundle/GMSCacheStorage.momd/Storage.omo'

[INFO]  2016-02-29 23:35:45.407 salla[21597:310258] Google Maps SDK for iOS version: 1.10.17867.0
[INFO]  2016-02-29 23:35:45.407 salla[21597:310258] New version of Google Maps SDK for iOS available: 1.12.23066.0
`
```

**Comment by hansemannn** [comment] 2016-02-29 22:03
The latest version is 2.0.1, which does not need the bundle to be copies manually. Please try that first. I also just pushed changes for the upcoming 2.1.0 which you could try.

**Comment by abada** [comment] 2016-02-29 22:04
Thank you for fast reply :)

But `V2.0.1` not working in `TISDK 5.2.0GA`

**Comment by hansemannn** [comment] 2016-02-29 22:10
Got it! It's the same issue as #8 , related to https://jira.appcelerator.org/browse/TIMOB-19694.

**Comment by hansemannn** [comment] 2016-02-29 22:11
Closing this issue as duplicate of the above issue, so we are in sync with the discussion.

**Closed by hansemannn** 2016-02-29 22:11 UTC
Labels: bug
