### ISSUE TITLE
Issue: new zoom level not included in "regionchanged" event

### ISSUE THREAD

**Issue by Mobilizr** [hansemannn/ti.googlemaps#56] opened 2016-11-28 02:57 UTC
When the user changes the region position and zoom level, I cannot seem to locate the current zoom level used on the map.

I would expect the "regionchanged" event to include the new zoom level.

But also is there a way to retrieve the current zoom level being used, even outside the regionchanged event? If I look at the map object, the map.region.zoom level is the zoom the map was originally created with - not the latest zoom level.

I need to store this so that the next time the app is opened it returns the user to their last selected region and zoom level.

**Comment by hansemannn** [comment] 2016-11-28 10:51
Thx! This is a dupe of #33; the old annotation references are returned instead of the new one. I hope I can find to continue working on the fix this week, keeping you update in the linked issue.

**Closed by hansemannn** 2016-11-28 10:51 UTC
