### ISSUE TITLE
Dragmove Event

### ISSUE THREAD

**Issue by dave101** [hansemannn/ti.googlemaps#50] opened 2016-08-26 06:13 UTC
When dragging an annotation, the callback on the 'dragmove' event does not display the updated coordinates at always stays at the original coordinates:

mapview.addEventListener('dragmove',function(e){
        Ti.API.warn(JSON.stringify(e.annotation));
});
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}
[WARN] :   {"longitude":145.50242349500002,"latitude":-37.83994674682617}

**Comment by hansemannn** [comment] 2016-08-26 21:27
Duplicate of https://github.com/hansemannn/ti.googlemaps/issues/33, please follow that one, thanks!

**Closed by hansemannn** 2016-08-26 21:27 UTC
